export const mapPizzaIngredientsToName = {
  PINEAPPLE: "сочные ананасы",
  MOZZARELLA: "сливочная моцарелла",
  PEPERONI: "пикантная пепперони",
  GREEN_PEPPER: "сладкий перец",
  MUSHROOMS: "шампиньоны",
  BASIL: "итальянские травы",
  CHEDDAR: "сыр чеддер",
  PARMESAN: "сыр пармезан",
  FETA: "кубики феты",
  HAM: "ветчина",
  PICKLE: "маринованные огурчики",
  TOMATO: "свежие томаты",
  BACON: "бекон",
  ONION: "лук",
  CHILE: "острый перец халапеньо",
  SHRIMPS: "креветки",
  CHICKEN_FILLET: "куриное филе",
  MEATBALLS: "митболы",
} as const;
